# -*- coding: utf-8 -*-
"""SVD_PCA_MSDS1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14U2y0DcS4bERV9CtGEnNro2QT8vYkg5F
"""

import numpy as np

X = np.rint(12*np.random.rand(6,5))
X

"""## SVD"""

[U,S,Vt] = np.linalg.svd(X)

Vt

S

D = Vt[0:3,:].T
D

"""## C = X*D"""

C = np.dot(X,D)
C

print(C.shape)

X_estim = np.dot(C,D.T)
X_estim

"""# Fonction PCA-SVD"""

def SVD_PCA(X,n_comp):
    [U,S,Vt] = np.linalg.svd(X)
    D = Vt[0:n_comp,:].T
    C = np.dot(X,D)
    dif = X - np.dot(C, D.T)
    err = np.linalg.norm(dif, 'fro')
    return [D,C,err/(X.shape[0]*n_comp)]

X

X = np.rint(12*np.random.rand(10,8))
X

[D,C,err] = SVD_PCA(X, 5)

err

D

C

X_estim2 = np.dot(C, D.T)
X_estim2





